### ISSUE TITLE
Enable auto-scaling based on CloudWatch Events

### ISSUE THREAD

**Issue by arun-gupta** [jpignata/fargate#48]
It would be great to enable service auto-scaling based upon CloudWatch events. For example, CPU or memory usage reaching a certain threshold.

**Comment by Mihailoff** [comment]
https://aws.github.io/copilot-cli/docs/include/common-svc-fields/

```
count:
  range: 1-10
  cpu_percentage: 70
  memory_percentage: 80
  requests: 10000
  response_time: 2s
```
